version: "3"
services:
  videos-gui:
    image: videos-gui
    ports:
      - "80:80"
  videos-service:
    image: videos-service
    expose:
      - "4001"
    ports:
      - "4001:4001"
    links:
      - mongo-db
    environment:
      - NFS_DIR=/tmp
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
  mongo-db:
    image: mongo
    expose:
      - "27017"
